### PR TITLE
Most Akkimari recipes

### PR DESCRIPTION
**Pull request by ghost**
Added recipes for most of Akkimari racial items, changed past recipes to include scavenging mechanics. Recipes may be unbalanced, need more testing and feedback.

### CODE REVIEW

**Comment by Dovahkiinzord** [comment]
Whoa beautiful!❤️ I was waiting for updates on the Akkimari for so long! Thank you so much! ⭐

**Comment by ghost** [comment]
Sorry for all this mess, I feel like some recipes need balancing and some things may be different from what the mod creator intended. I'm leaving things as they are now. Akkimari might be a little more playable now.

**Comment by Dovahkiinzord** [comment]
thank you very much for the hard work! I am super happy that I finally will be able to play as Akkimari! Big thank you!

**Comment by smartintruesdell** [comment]
I pulled this branch over into my own fork for testing and found a couple small issues:

### Connector Strips

A few Akkimari recipes are now requiring Connector Strips (`items/crafting/connectorstrip.item`), but the Akkimari don't have a way to create this (that I could find) without also learning the Alliance/other crafting tables. Easy solution is adding `akkimaricrafting` to the groups for `connectorstrip`.

### Broken Recipes

There are a handful of recipes that fail to load:

```
[14:25:52.884] [Error] Could not load recipe /recipes/akkimari/akkimaricrafting/weapons/ranged/akkimari-nailgun.recipe: (ItemException) No such item 'akkimarcircuitry'
[14:25:54.186] [Error] Could not load recipe /recipes/akkimari/akkimaricrafting2/armor/akkimari-tier4head.recipe: (ItemException) No such item 'akkimaricircuit'
[14:25:55.515] [Error] Could not load recipe /recipes/akkimari/akkimaricrafting2/armor/akkimari-tier4chest.recipe: (ItemException) No such item 'akkimaricircuit'
```

Looks like it's just typos.

**Pull request closed without merging**
